# Generated by Django 3.1b1 on 2020-06-21 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_board_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='votedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.board'),
        ),
        migrations.AddField(
            model_name='post',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='voted_post',
            field=models.ManyToManyField(through='posts.VotedPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='votedpost',
            unique_together={('user', 'post')},
        ),
    ]
