# Generated by Django 3.1b1 on 2020-06-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200621_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='voted_post',
            new_name='post_voted_user',
        ),
    ]
