# Generated by Django 2.2.13 on 2020-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('SUPER', 'super'), ('STAFF', 'STAFF'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=6),
        ),
    ]
